# see research.src.data.datamodule:get_dataset_iter
token_size: 5000
num_bucket: 32
batch_size: -1
shuffle: true
no_drop: false
fully_shuffle: ~
num_workers: ${in_debugger:0,8}
pin_memory: true
force_same_len: false
