best_watcher:
  _target_: src.utils.callback.BestWatcherCallback
  monitor: ${watch_field}
  mode: ${watch_mode}
  hint: true
  save:
    dirpath: checkpoint
    filename: "${ckpt_name:'{epoch}-{step}-{${watch_field}:.2f}',${watch_field},${runner.test_when_val}}"
    start_patience: 10
  write: 'new'
  report: true
