defaults:
  - logger: ~
  - callbacks:
    - progressbar
  - override /hydra/job_logging@_global_.hydra.job_logging: nofile

_target_: src.utils.fn.instantiate_trainer

checkpoint_callback: false
logger: ~

gpus: 1
precision: 32
resume_from_checkpoint: ~

# following are settings you should not touch in most cases
accelerator: ${accelerator:${.gpus}}
terminate_on_nan: true
replace_sampler_ddp: false
weights_summary: ~
